package com.venefast.springboot.cinemamcpclient.app.services.impl;

import com.venefast.springboot.cinemamcpclient.app.models.dtos.CinemaPromptRequestDto;
import com.venefast.springboot.cinemamcpclient.app.models.dtos.CinemaPromptResponseDto;
import com.venefast.springboot.cinemamcpclient.app.models.dtos.CinemaStatusDto;
import com.venefast.springboot.cinemamcpclient.app.services.CinemaAssistantService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.Instant;

/**
 * Service implementation orchestrating Spring AI ChatClient, Ollama model inference,
 * and automated MCP tool invocation against Movie MCP Server.
 */
@Service
public class CinemaAssistantServiceImpl implements CinemaAssistantService {

    private static final Logger log = LoggerFactory.getLogger(CinemaAssistantServiceImpl.class);

    private final ChatClient chatClient;

    @Value("${spring.ai.ollama.chat.options.model:llama3.2}")
    private String ollamaModel = "llama3.2";

    @Value("${spring.ai.mcp.client.streamable-http.connections.movie-server.url:http://localhost:8090}")
    private String mcpServerUrl = "http://localhost:8090";

    @Value("${spring.ai.mcp.client.enabled:true}")
    private boolean mcpClientEnabled = true;

    public CinemaAssistantServiceImpl(ChatClient chatClient) {
        this.chatClient = chatClient;
    }

    @Override
    public CinemaPromptResponseDto askAssistant(CinemaPromptRequestDto request) {
        log.info("Processing user query via ChatClient: prompt='{}', preference='{}'",
                request.prompt(), request.userPreference());

        try {
            var promptSpec = chatClient.prompt().user(u -> {
                u.text(request.prompt());
                if (request.userPreference() != null && !request.userPreference().isBlank()) {
                    u.param("preference", request.userPreference());
                }
            });

            String content = promptSpec.call().content();

            return new CinemaPromptResponseDto(
                content != null ? content : "No response generated by the model.",
                ollamaModel,
                Instant.now().toString()
            );
        } catch (Exception ex) {
            log.error("Error communicating with Ollama or Movie MCP Server: {}", ex.getMessage(), ex);
            return new CinemaPromptResponseDto(
                "Unable to complete request. Please verify that Ollama is running and Movie MCP Server is reachable. Details: " + ex.getMessage(),
                ollamaModel,
                Instant.now().toString()
            );
        }
    }

    @Override
    public CinemaPromptResponseDto recommendByGenre(String genre) {
        String query = String.format(
            "Please check the movie catalog using your tools and recommend the best movies in the '%s' genre. Include titles, ratings, and screening schedules if available.",
            genre != null && !genre.isBlank() ? genre : "all"
        );
        return askAssistant(new CinemaPromptRequestDto(query, genre));
    }

    @Override
    public CinemaStatusDto getStatus() {
        return new CinemaStatusDto(
            "UP",
            ollamaModel,
            mcpServerUrl,
            mcpClientEnabled
        );
    }
}
